name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build project
      run: dotnet build -c Release

    - name: Lint C# code
      run: dotnet format --verify-no-changes --exclude ACMESharpCore --verbosity detailed --no-restore

    # - name: Lint Bicep template
    #   run: az bicep build -f azuredeploy.bicep && git diff --exit-code --quiet